export const JOIN_SPACE = 'JOIN_SPACE';
export const ALL_PARTICIPANTS = 'ALL_PARTICIPANTS';
export const SENDING_SIGNAL = 'SENDING_SIGNAL';
export const USER_JOINED = 'USER_JOINED';
export const RETURNING_SIGNAL = 'RETURNING_SIGNAL';
export const RECEIVING_RETURNED_SIGNAL = 'RECEIVING_RETURNED_SIGNAL';
