export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as ResendVerificationLink } from './ResendVerificationLink';
export { default as ForgotPassword } from './ForgotPassword';
export { default as NewPassword } from './NewPassword';
export { default as VerifyAccount } from './VerifyAccount';
export { default as Space } from './Space';
export { default as Spaces } from './Spaces';
